[tool.poetry]
name = "bbctl"
version = "0.1.0"
description = ""
authors = ["Luis Giraldo <giraldo.luisdavid@gmail.com.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
