name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install .
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name bbctl --hidden-import=click --hidden-import=requests --hidden-import=python-dotenv bbctl/main.py
    
    - name: Generate SHA-256 checksum
      run: |
        cd dist
        sha256sum bbctl > bbctl-linux-checksum.txt
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bbctl-linux
        path: |
          dist/bbctl
          dist/bbctl-linux-checksum.txt
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.run_number }}
        name: Build ${{ github.run_number }}
        files: |
          dist/bbctl
          dist/bbctl-linux-checksum.txt
        body: |
          # Build ${{ github.run_number }}
          
          Automated build from commit: ${{ github.sha }}
          
          ## Installation
          
          ```bash
          # Download the binary
          curl -LO https://github.com/${{ github.repository }}/releases/download/${{ github.run_number }}/bbctl
          
          # Make it executable
          chmod +x bbctl
          
          # Move to a directory in your PATH
          sudo mv bbctl /usr/local/bin/
          ```
          
          Check the included checksum file to verify the download.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}